### ISSUE TITLE
"Invalid Feed URL" in uTorrent

### ISSUE THREAD

**Issue by dzg** [Theadd/TorrentzRSS#4]
Awesome system!

But when I try to paste the RSS feed URL in uTorrent (Mac), it says "Invalid feed URL"

My URL is:
http://37.187.9.5:8080/TorrentzRSS/process.php?f=rss&p=feed-1-t15-d120-rk-Lm&r=&q=%22Better%20Call%20Saul%22%20|%20%22Family%20Guy%22%20|%20%22Game%20of%20Thrones%22%20|%20%22Homeland%22%20|%20%22Last%20Week%20Tonight%22%20|%20%22Masters%20of%20Sex%22%20|%20%22Modern%20Family%22%20|%20%22Orange%20Is%20the%20New%20Black%22%20|%20%22South%20Park%22

**Comment by Theadd** [comment]
Thank you! =)

Well, I don't have Mac but I've installed uTorrent in Windows and tried your URL --successfully at first--. If you don't really care about it, here is your **quick fix**:
- Use a shorter search query. (AKA remove the last part of your query, `| "Orange Is the New Black" | "South Park"`)

**Explained:**
If you open your URL in _Google Chrome_, you will be able to see the generated code for your _RSS_. Keep refreshing the page **[F5]**. Once every 5/6 times you pressed _[F5]_ you will notice that the generated code is too short.

There, you can see the error:

```
<errors>
    <item>Torrentz.eu says: Your search query is too long.</item>
</errors>
```

It's really odd, some times work and other times **torrentz.eu** complaints of being too long. It makes no sense but I can't fix that.

**Other than that**, you might want to follow the step by step **Guided Tour: The power of query intersection** on the main page to generate RSS feeds that only have the latest episode of your specified TV shows in your desired quality, like [this one](http://37.187.9.5:8080/TorrentzRSS/process.php?f=rss&p=feedA-1-t15-d120-rk-Lm&r=if8d57fcf019ee04c40131fd3fae7ad70&q=%22Better%20Call%20Saul%22%20|%20%22Family%20Guy%22%20|%20%22Game%20of%20Thrones%22%20|%20%22Homeland%22%20|%20%22Last%20Week%20Tonight%22%20|%20%22Masters%20of%20Sex%22%20|%20%22Modern%20Family%22), using the TV Shows that you specified in your URL, except the last two. ([Here](http://theadd.github.io/TorrentzRSS/?p=feedA-1-t15-d120-rk-Lm&r=if8d57fcf019ee04c40131fd3fae7ad70&q=%22Better%20Call%20Saul%22%20|%20%22Family%20Guy%22%20|%20%22Game%20of%20Thrones%22%20|%20%22Homeland%22%20|%20%22Last%20Week%20Tonight%22%20|%20%22Masters%20of%20Sex%22%20|%20%22Modern%20Family%22#results) is the _WEB_ link).
